#!/usr/bin/env bash
set -euo pipefail
shopt -s globstar nullglob

if git diff --quiet; then
	echo "No changes"
	exit 1
fi

SCRIPT_DIR="$(dirname -- "$(realpath -- "${BASH_SOURCE[0]}")")"

for FILE in "$SCRIPT_DIR"/**/*.nix; do
	TARGET="/etc/nixos/${FILE#$SCRIPT_DIR/}"

	if [[ -L "$TARGET" && ! -e "$TARGET" ]]; then
		echo "Removing existing $TARGET"
		sudo rm "$TARGET"

		echo "Linking $FILE to $TARGET"
		sudo ln -s "$FILE" "$TARGET"
	fi

done

sudo nixos-rebuild switch

git commit -am "Working Build $(date '+%d.%m.%Y %H:%M:%S')"
git push

